/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package flightcontroller;

/**
 *
 * @author nacholozanogarcia
 */
public class jpBienvenida extends javax.swing.JPanel {

    /**
     * Creates new form jpBienvenida
     */
    public jpBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBienvenido = new javax.swing.JLabel();
        jLNombreEmpleado = new javax.swing.JLabel();
        jTextNombreEmpleado = new javax.swing.JTextField();
        jLIdEmpleado = new javax.swing.JLabel();
        jTextIdEmpleado = new javax.swing.JTextField();
        jLPuestoTrabajo = new javax.swing.JLabel();
        jTextPuestoTrabajo = new javax.swing.JTextField();
        jBPanelDatosTecnicos = new javax.swing.JButton();
        jBPanelEconomia = new javax.swing.JButton();
        jBPanelEmpleados = new javax.swing.JButton();
        jBPanelPrincipal = new javax.swing.JButton();
        jBCerrarPrograma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBienvenido.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBienvenido.setText("Bienvenido/a");
        jLBienvenido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 30));

        jLNombreEmpleado.setText("Nombre de empleado");
        jLNombreEmpleado.setPreferredSize(new java.awt.Dimension(156, 26));
        add(jLNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jTextNombreEmpleado.setText("Lara Leist");
        jTextNombreEmpleado.setEnabled(false);
        jTextNombreEmpleado.setPreferredSize(new java.awt.Dimension(156, 26));
        add(jTextNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 80, -1, -1));

        jLIdEmpleado.setText("ID de empleado");
        jLIdEmpleado.setPreferredSize(new java.awt.Dimension(156, 26));
        add(jLIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jTextIdEmpleado.setText("001");
        jTextIdEmpleado.setEnabled(false);
        jTextIdEmpleado.setPreferredSize(new java.awt.Dimension(156, 26));
        add(jTextIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 130, -1, -1));

        jLPuestoTrabajo.setText("Puesto de trabajo");
        jLPuestoTrabajo.setPreferredSize(new java.awt.Dimension(156, 26));
        add(jLPuestoTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jTextPuestoTrabajo.setText("Piloto - Airbus A320");
        jTextPuestoTrabajo.setEnabled(false);
        add(jTextPuestoTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 180, -1, -1));

        jBPanelDatosTecnicos.setText("Datos Técnicos Flota");
        add(jBPanelDatosTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jBPanelEconomia.setText("Datos Economicos");
        jBPanelEconomia.setMaximumSize(new java.awt.Dimension(176, 29));
        jBPanelEconomia.setMinimumSize(new java.awt.Dimension(176, 29));
        jBPanelEconomia.setPreferredSize(new java.awt.Dimension(176, 29));
        add(jBPanelEconomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jBPanelEmpleados.setText("Gestión de Empleados");
        jBPanelEmpleados.setMaximumSize(new java.awt.Dimension(176, 29));
        jBPanelEmpleados.setMinimumSize(new java.awt.Dimension(176, 29));
        jBPanelEmpleados.setPreferredSize(new java.awt.Dimension(176, 29));
        add(jBPanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jBPanelPrincipal.setText("Cerrar Sesión");
        jBPanelPrincipal.setMaximumSize(new java.awt.Dimension(176, 29));
        jBPanelPrincipal.setMinimumSize(new java.awt.Dimension(176, 29));
        jBPanelPrincipal.setPreferredSize(new java.awt.Dimension(176, 29));
        add(jBPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jBCerrarPrograma.setText("Cerrar Programa");
        jBCerrarPrograma.setPreferredSize(new java.awt.Dimension(176, 29));
        add(jBCerrarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú de acciones");
        jLabel1.setMaximumSize(new java.awt.Dimension(176, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(176, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(176, 29));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 20, 230));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrarPrograma;
    private javax.swing.JButton jBPanelDatosTecnicos;
    private javax.swing.JButton jBPanelEconomia;
    private javax.swing.JButton jBPanelEmpleados;
    private javax.swing.JButton jBPanelPrincipal;
    private javax.swing.JLabel jLBienvenido;
    private javax.swing.JLabel jLIdEmpleado;
    private javax.swing.JLabel jLNombreEmpleado;
    private javax.swing.JLabel jLPuestoTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextIdEmpleado;
    private javax.swing.JTextField jTextNombreEmpleado;
    private javax.swing.JTextField jTextPuestoTrabajo;
    // End of variables declaration//GEN-END:variables
}
