/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package flightcontroller;

/**
 *
 * @author nacholozanogarcia
 */
public class jpMantenimiento extends javax.swing.JPanel {

    /**
     * Creates new form jpMantenimiento
     */
    public jpMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboModeloAvion = new javax.swing.JComboBox<>();
        jLSeleccionarModelo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableInformacionAvion = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jComboModeloAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boeing 747-800", "Boeing 767-200", "McDonell Douglas DC 10", "Antonov An-225", "Airbus A220", "Airbus A300", "Airbus A300-600ST Beluga", "Airbus Beluga XL", "Airbus A310", "Airbus A318", "Airbus A319", "Airbus A320", "Airbus A321", "Airbus A330", "Airbus A340", "Airbus A350", "Airbus A380", " " }));
        jComboModeloAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboModeloAvionActionPerformed(evt);
            }
        });

        jLSeleccionarModelo.setText("Selecciona un modelo de avión");

        JTableInformacionAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Airbus A380", "700", "310.000 Litros", "600 L/100KM", "9 Abril 2009", "24 Noviembre 2025", "3 Agosto 2021"},
                {"02", "Airbus A380", "750", "310.000Litros", "650L/100KM", "12 Octubre 2010", "10 Noviembre 2028", "1 Julio 2021"},
                {"03", "Airbus A380", "650", "310.000 Litros", "590L/100KM", "1 Febrero 2006", "27 Diciembre 2023", "23 Noviembre 2021"}
            },
            new String [] {
                "ID", "Modelo", "Numero Asientos", "Capacidad Carburante", "Consumo", "Fecha Primer Servicio", "Fecha Ultimo Servicio", "Fecha Mantenimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableInformacionAvion);

        jButton1.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLSeleccionarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboModeloAvion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLSeleccionarModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboModeloAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboModeloAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboModeloAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboModeloAvionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableInformacionAvion;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboModeloAvion;
    private javax.swing.JLabel jLSeleccionarModelo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
